version: "3.7"

services:
  japi-docs:
    image: sv443-network/japi-docs:latest
    container_name: japi-docs
    restart: unless-stopped
    ports:
      - 8059:8059
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./japi-docs:/app
