name: "Deploy Stage"

on:
  workflow_dispatch:

jobs:
  deploy-stage:
    name: Deploy Stage
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          # TODO: https://nicwortel.nl/blog/2022/continuous-deployment-to-kubernetes-with-github-actions
          method: service-account
          k8s-url: <server-url>
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
          namespace: default
          # TODO:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/ingress.yaml
            kubernetes/service.yaml
          images: |
            ghcr.io/username/package:${{ github.sha }}
